name: Release

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
    test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: 3.12
        - name: Install setuptools and
          run: |
            python -m pip install --upgrade setuptools wheel
            python -m pip install -r requirements-dev.txt
        - name: Test
          run: pytest
