name: Release

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
    test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: 3.12
        - name: Install setuptools and
          run: |
            python -m pip install --upgrade setuptools wheel
            python -m pip install -r requirements-dev.txt
        - name: Test
          run: pytest

    publish:
      name: Publish
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      needs: test
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: 3.12
        - name: Install setuptools and
          run: python -m pip install --upgrade setuptools wheel
        - name: Build a binary wheel and a source tarball
          run: python setup.py build sdist bdist_wheel
        - name: Publish distribution 📦 to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
